### ISSUE TITLE
Substitute diode for ZPD8V2 ?

### ISSUE THREAD

**Issue by wpuziewicz** [matafonoff/J1850-VPW-Arduino-Transceiver-Library#5]
Hi,

I'm looking to build this project, but I can't find a source for the ZPD8V2 diode listed in the schematic.  I found a datasheet for it but I'm stumped at the Digikey spec search.  I don't know enough to pick a substitute.  Can you recommend another diode that will work in its place?

Thanks

**Comment by matafonoff** [comment]
You need any zener diod with stabilization voltage at around 7.5-8.2v.

**Comment by wpuziewicz** [comment]
Thanks for the quick response!

For anyone else with the same question, here is what I ordered from Digikey.  I got a 7.5v and an 8.2v just in case one works better than the other.

1N5344BRLGOSCT-ND‎
‎1N5344BRLG‎
DIODE ZENER 8.2V 5W AXIAL 

1N5343BRLGOSCT-ND‎
‎1N5343BRLG‎
DIODE ZENER 7.5V 5W AXIAL

**Comment by Lorenzch** [comment]
@wpuziewicz 

Hello. I was in the same problem as you so I bought the ‎1N5344BRLG (8.2 volts), but my circuit seems not to be working because even though I connected everything correctly when I open the sniff sketch and open the console I get "WRITE J1850_ERR_RECV_NOT_CONFIGURATED"

I don't understand a write error when I'm just trying to read (sniff), so I was wondering if my problem has something to do with de zener. 

What diode worked for you?
